/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as ClanNameRouteImport } from './routes/clan/$name'
import { Route as GroupNameRouteImport } from './routes/group/$name'
import { Route as InfoAliasRouteImport } from './routes/info/alias'
import { Route as InfoDiscordBotRouteImport } from './routes/info/discord-bot'
import { Route as InfoGuideRouteImport } from './routes/info/guide'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ClanNameRoute = ClanNameRouteImport.update({
  id: '/clan/$name',
  path: '/clan/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupNameRoute = GroupNameRouteImport.update({
  id: '/group/$name',
  path: '/group/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoAliasRoute = InfoAliasRouteImport.update({
  id: '/info/alias',
  path: '/info/alias',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoDiscordBotRoute = InfoDiscordBotRouteImport.update({
  id: '/info/discord-bot',
  path: '/info/discord-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoGuideRoute = InfoGuideRouteImport.update({
  id: '/info/guide',
  path: '/info/guide',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/clan/$name': typeof ClanNameRoute
  '/group/$name': typeof GroupNameRoute
  '/info/alias': typeof InfoAliasRoute
  '/info/discord-bot': typeof InfoDiscordBotRoute
  '/info/guide': typeof InfoGuideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/clan/$name': typeof ClanNameRoute
  '/group/$name': typeof GroupNameRoute
  '/info/alias': typeof InfoAliasRoute
  '/info/discord-bot': typeof InfoDiscordBotRoute
  '/info/guide': typeof InfoGuideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/clan/$name': typeof ClanNameRoute
  '/group/$name': typeof GroupNameRoute
  '/info/alias': typeof InfoAliasRoute
  '/info/discord-bot': typeof InfoDiscordBotRoute
  '/info/guide': typeof InfoGuideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/clan/$name'
    | '/group/$name'
    | '/info/alias'
    | '/info/discord-bot'
    | '/info/guide'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/clan/$name'
    | '/group/$name'
    | '/info/alias'
    | '/info/discord-bot'
    | '/info/guide'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/clan/$name'
    | '/group/$name'
    | '/info/alias'
    | '/info/discord-bot'
    | '/info/guide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  ClanNameRoute: typeof ClanNameRoute
  GroupNameRoute: typeof GroupNameRoute
  InfoAliasRoute: typeof InfoAliasRoute
  InfoDiscordBotRoute: typeof InfoDiscordBotRoute
  InfoGuideRoute: typeof InfoGuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clan/$name': {
      id: '/clan/$name'
      path: '/clan/$name'
      fullPath: '/clan/$name'
      preLoaderRoute: typeof ClanNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$name': {
      id: '/group/$name'
      path: '/group/$name'
      fullPath: '/group/$name'
      preLoaderRoute: typeof GroupNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/alias': {
      id: '/info/alias'
      path: '/info/alias'
      fullPath: '/info/alias'
      preLoaderRoute: typeof InfoAliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/discord-bot': {
      id: '/info/discord-bot'
      path: '/info/discord-bot'
      fullPath: '/info/discord-bot'
      preLoaderRoute: typeof InfoDiscordBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/guide': {
      id: '/info/guide'
      path: '/info/guide'
      fullPath: '/info/guide'
      preLoaderRoute: typeof InfoGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  ClanNameRoute: ClanNameRoute,
  GroupNameRoute: GroupNameRoute,
  InfoAliasRoute: InfoAliasRoute,
  InfoDiscordBotRoute: InfoDiscordBotRoute,
  InfoGuideRoute: InfoGuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
