export const QuestState = {
  NOT_STARTED: 0,
  IN_PROGRESS: 1,
  FINISHED: 2,
} as const;
export type QuestState = (typeof QuestState)[keyof typeof QuestState];

export function getQuestStateFromIndex(index?: number) {
  switch (index) {
    case 0:
      return QuestState.NOT_STARTED;
    case 1:
      return QuestState.IN_PROGRESS;
    case 2:
      return QuestState.FINISHED;
    default:
      return QuestState.NOT_STARTED;
  }
}

export function getQuestById(id: number) {
  return QUESTS.find((quest) => quest.id === id);
}

export const QuestType = {
  FREE: 0,
  MEMBERS: 1,
  MINI: 2,
} as const;
export type QuestType = (typeof QuestType)[keyof typeof QuestType];

export type Quest = {
  id: number;
  name: string;
  type: QuestType;
  points: number;
};
// prettier-ignore
export const QUESTS = [
  // FREE quests
  { id: 6, name: "Below Ice Mountain", points: 1, type: QuestType.FREE },
  { id: 10, name: "Black Knights' Fortress", points: 3, type: QuestType.FREE },
  { id: 17, name: "Cook's Assistant", points: 1, type: QuestType.FREE },
  { id: 18, name: "The Corsair Curse", points: 2, type: QuestType.FREE },
  { id: 25, name: "Demon Slayer", points: 3, type: QuestType.FREE },
  { id: 30, name: "Doric's Quest", points: 1, type: QuestType.FREE },
  { id: 31, name: "Dragon Slayer I", points: 2, type: QuestType.FREE },
  { id: 44, name: "Ernest the Chicken", points: 4, type: QuestType.FREE },
  { id: 64, name: "Goblin Diplomacy", points: 5, type: QuestType.FREE },
  { id: 76, name: "Imp Catcher", points: 1, type: QuestType.FREE },
  { id: 83, name: "The Knight's Sword", points: 1, type: QuestType.FREE },
  { id: 94, name: "Misthalin Mystery", points: 1, type: QuestType.FREE },
  { id: 108, name: "Pirate's Treasure", points: 2, type: QuestType.FREE },
  { id: 112, name: "Prince Ali Rescue", points: 3, type: QuestType.FREE },
  { id: 120, name: "The Restless Ghost", points: 1, type: QuestType.FREE },
  { id: 121, name: "Romeo & Juliet", points: 5, type: QuestType.FREE },
  { id: 125, name: "Rune Mysteries", points: 1, type: QuestType.FREE },
  { id: 131, name: "Sheep Shearer", points: 1, type: QuestType.FREE },
  { id: 132, name: "Shield of Arrav", points: 1, type: QuestType.FREE },
  { id: 155, name: "Vampyre Slayer", points: 3, type: QuestType.FREE },
  { id: 161, name: "Witch's Potion", points: 1, type: QuestType.FREE },
  { id: 162, name: "X Marks the Spot", points: 1, type: QuestType.FREE },

  // MEMBERS quests
  { id: 0, name: "Animal Magnetism", points: 1, type: QuestType.MEMBERS },
  {
    id: 1,
    name: "Another Slice of H.A.M.",
    points: 1,
    type: QuestType.MEMBERS,
  },
  { id: 3, name: "The Ascent of Arceuus", points: 1, type: QuestType.MEMBERS },
  { id: 3513, name: "At First Light", points: 1, type: QuestType.MEMBERS },
  { id: 168, name: "Beneath Cursed Sands", points: 2, type: QuestType.MEMBERS },
  { id: 7, name: "Between a Rock...", points: 2, type: QuestType.MEMBERS },
  {
    id: 8,
    name: "Big Chompy Bird Hunting",
    points: 2,
    type: QuestType.MEMBERS,
  },
  { id: 9, name: "Biohazard", points: 3, type: QuestType.MEMBERS },
  { id: 11, name: "Bone Voyage", points: 1, type: QuestType.MEMBERS },
  { id: 12, name: "Cabin Fever", points: 2, type: QuestType.MEMBERS },
  { id: 3450, name: "Children of the Sun", points: 1, type: QuestType.MEMBERS },
  { id: 13, name: "Client of Kourend", points: 1, type: QuestType.MEMBERS },
  { id: 14, name: "Clock Tower", points: 1, type: QuestType.MEMBERS },
  { id: 15, name: "Cold War", points: 1, type: QuestType.MEMBERS },
  { id: 16, name: "Contact!", points: 1, type: QuestType.MEMBERS },
  {
    id: 19,
    name: "Creature of Fenkenstrain",
    points: 2,
    type: QuestType.MEMBERS,
  },
  { id: 3937, name: "The Curse of Arrav", points: 2, type: QuestType.MEMBERS },
  {
    id: 22,
    name: "Darkness of Hallowvale",
    points: 2,
    type: QuestType.MEMBERS,
  },
  { id: 3711, name: "Death on the Isle", points: 2, type: QuestType.MEMBERS },
  { id: 23, name: "Death Plateau", points: 1, type: QuestType.MEMBERS },
  {
    id: 24,
    name: "Death to the Dorgeshuun",
    points: 1,
    type: QuestType.MEMBERS,
  },
  { id: 3466, name: "Defender of Varrock", points: 2, type: QuestType.MEMBERS },
  { id: 26, name: "The Depths of Despair", points: 1, type: QuestType.MEMBERS },
  { id: 27, name: "Desert Treasure I", points: 3, type: QuestType.MEMBERS },
  {
    id: 2343,
    name: "Desert Treasure II - The Fallen Empire",
    points: 5,
    type: QuestType.MEMBERS,
  },
  { id: 28, name: "Devious Minds", points: 1, type: QuestType.MEMBERS },
  { id: 29, name: "The Dig Site", points: 2, type: QuestType.MEMBERS },
  { id: 32, name: "Dragon Slayer II", points: 5, type: QuestType.MEMBERS },
  { id: 33, name: "Dream Mentor", points: 2, type: QuestType.MEMBERS },
  { id: 34, name: "Druidic Ritual", points: 4, type: QuestType.MEMBERS },
  { id: 35, name: "Dwarf Cannon", points: 1, type: QuestType.MEMBERS },
  { id: 36, name: "Eadgar's Ruse", points: 1, type: QuestType.MEMBERS },
  { id: 37, name: "Eagles' Peak", points: 2, type: QuestType.MEMBERS },
  { id: 38, name: "Elemental Workshop I", points: 1, type: QuestType.MEMBERS },
  { id: 39, name: "Elemental Workshop II", points: 1, type: QuestType.MEMBERS },
  { id: 40, name: "Enakhra's Lament", points: 2, type: QuestType.MEMBERS },
  { id: 42, name: "Enlightened Journey", points: 1, type: QuestType.MEMBERS },
  {
    id: 3713,
    name: "Ethically Acquired Antiquities",
    points: 1,
    type: QuestType.MEMBERS,
  },
  { id: 45, name: "The Eyes of Glouphrie", points: 2, type: QuestType.MEMBERS },
  {
    id: 46,
    name: "Fairytale I - Growing Pains",
    points: 2,
    type: QuestType.MEMBERS,
  },
  {
    id: 47,
    name: "Fairytale II - Cure a Queen",
    points: 2,
    type: QuestType.MEMBERS,
  },
  { id: 48, name: "Family Crest", points: 1, type: QuestType.MEMBERS },
  { id: 50, name: "The Feud", points: 1, type: QuestType.MEMBERS },
  { id: 51, name: "Fight Arena", points: 2, type: QuestType.MEMBERS },
  { id: 5189, name: "The Final Dawn", points: 3, type: QuestType.MEMBERS },
  { id: 52, name: "Fishing Contest", points: 1, type: QuestType.MEMBERS },
  { id: 53, name: "Forgettable Tale...", points: 2, type: QuestType.MEMBERS },
  { id: 54, name: "The Forsaken Tower", points: 1, type: QuestType.MEMBERS },
  { id: 55, name: "The Fremennik Exiles", points: 2, type: QuestType.MEMBERS },
  { id: 56, name: "The Fremennik Isles", points: 1, type: QuestType.MEMBERS },
  { id: 57, name: "The Fremennik Trials", points: 3, type: QuestType.MEMBERS },
  { id: 180, name: "The Garden of Death", points: 1, type: QuestType.MEMBERS },
  {
    id: 58,
    name: "Garden of Tranquillity",
    points: 2,
    type: QuestType.MEMBERS,
  },
  { id: 60, name: "Gertrude's Cat", points: 1, type: QuestType.MEMBERS },
  { id: 61, name: "Getting Ahead", points: 1, type: QuestType.MEMBERS },
  { id: 62, name: "Ghosts Ahoy", points: 2, type: QuestType.MEMBERS },
  { id: 63, name: "The Giant Dwarf", points: 2, type: QuestType.MEMBERS },
  { id: 65, name: "The Golem", points: 1, type: QuestType.MEMBERS },
  { id: 66, name: "The Grand Tree", points: 5, type: QuestType.MEMBERS },
  {
    id: 67,
    name: "The Great Brain Robbery",
    points: 2,
    type: QuestType.MEMBERS,
  },
  { id: 68, name: "Grim Tales", points: 1, type: QuestType.MEMBERS },
  { id: 69, name: "The Hand in the Sand", points: 1, type: QuestType.MEMBERS },
  { id: 70, name: "Haunted Mine", points: 2, type: QuestType.MEMBERS },
  { id: 71, name: "Hazeel Cult", points: 1, type: QuestType.MEMBERS },
  {
    id: 3710,
    name: "The Heart of Darkness",
    points: 2,
    type: QuestType.MEMBERS,
  },
  { id: 72, name: "Heroes' Quest", points: 1, type: QuestType.MEMBERS },
  { id: 73, name: "Holy Grail", points: 2, type: QuestType.MEMBERS },
  { id: 74, name: "Horror from the Deep", points: 2, type: QuestType.MEMBERS },
  {
    id: 75,
    name: "Icthlarin's Little Helper",
    points: 2,
    type: QuestType.MEMBERS,
  },
  { id: 77, name: "In Aid of the Myreque", points: 2, type: QuestType.MEMBERS },
  {
    id: 79,
    name: "In Search of the Myreque",
    points: 2,
    type: QuestType.MEMBERS,
  },
  { id: 80, name: "Jungle Potion", points: 1, type: QuestType.MEMBERS },
  { id: 82, name: "King's Ransom", points: 1, type: QuestType.MEMBERS },
  { id: 81, name: "A Kingdom Divided", points: 2, type: QuestType.MEMBERS },
  { id: 165, name: "Land of the Goblins", points: 2, type: QuestType.MEMBERS },
  { id: 85, name: "Legends' Quest", points: 4, type: QuestType.MEMBERS },
  { id: 86, name: "Lost City", points: 3, type: QuestType.MEMBERS },
  { id: 87, name: "The Lost Tribe", points: 1, type: QuestType.MEMBERS },
  { id: 88, name: "Lunar Diplomacy", points: 2, type: QuestType.MEMBERS },
  {
    id: 91,
    name: "Making Friends with My Arm",
    points: 2,
    type: QuestType.MEMBERS,
  },
  { id: 92, name: "Making History", points: 3, type: QuestType.MEMBERS },
  { id: 3712, name: "Meat and Greet", points: 1, type: QuestType.MEMBERS },
  { id: 93, name: "Merlin's Crystal", points: 6, type: QuestType.MEMBERS },
  { id: 97, name: "Monk's Friend", points: 1, type: QuestType.MEMBERS },
  { id: 95, name: "Monkey Madness I", points: 3, type: QuestType.MEMBERS },
  { id: 96, name: "Monkey Madness II", points: 4, type: QuestType.MEMBERS },
  { id: 98, name: "Mountain Daughter", points: 2, type: QuestType.MEMBERS },
  { id: 99, name: "Mourning's End Part I", points: 2, type: QuestType.MEMBERS },
  {
    id: 100,
    name: "Mourning's End Part II",
    points: 2,
    type: QuestType.MEMBERS,
  },
  { id: 101, name: "Murder Mystery", points: 3, type: QuestType.MEMBERS },
  {
    id: 102,
    name: "My Arm's Big Adventure",
    points: 1,
    type: QuestType.MEMBERS,
  },
  { id: 103, name: "Nature Spirit", points: 2, type: QuestType.MEMBERS },
  {
    id: 104,
    name: "A Night at the Theatre",
    points: 2,
    type: QuestType.MEMBERS,
  },
  { id: 105, name: "Observatory Quest", points: 2, type: QuestType.MEMBERS },
  { id: 106, name: "Olaf's Quest", points: 1, type: QuestType.MEMBERS },
  { id: 107, name: "One Small Favour", points: 2, type: QuestType.MEMBERS },
  {
    id: 3425,
    name: "The Path of Glouphrie",
    points: 2,
    type: QuestType.MEMBERS,
  },
  { id: 3514, name: "Perilous Moons", points: 2, type: QuestType.MEMBERS },
  { id: 109, name: "Plague City", points: 1, type: QuestType.MEMBERS },
  {
    id: 110,
    name: "A Porcine of Interest",
    points: 1,
    type: QuestType.MEMBERS,
  },
  { id: 111, name: "Priest in Peril", points: 1, type: QuestType.MEMBERS },
  { id: 113, name: "The Queen of Thieves", points: 1, type: QuestType.MEMBERS },
  { id: 114, name: "Rag and Bone Man I", points: 1, type: QuestType.MEMBERS },
  { id: 115, name: "Rag and Bone Man II", points: 1, type: QuestType.MEMBERS },
  { id: 116, name: "Ratcatchers", points: 2, type: QuestType.MEMBERS },
  { id: 117, name: "Recipe for Disaster", points: 10, type: QuestType.MEMBERS },
  { id: 118, name: "Recruitment Drive", points: 1, type: QuestType.MEMBERS },
  { id: 119, name: "Regicide", points: 3, type: QuestType.MEMBERS },
  {
    id: 3515,
    name: "The Ribbiting Tale of a Lily Pad Labour Dispute",
    points: 1,
    type: QuestType.MEMBERS,
  },
  { id: 122, name: "Roving Elves", points: 1, type: QuestType.MEMBERS },
  { id: 123, name: "Royal Trouble", points: 1, type: QuestType.MEMBERS },
  { id: 124, name: "Rum Deal", points: 2, type: QuestType.MEMBERS },
  { id: 126, name: "Scorpion Catcher", points: 1, type: QuestType.MEMBERS },
  { id: 5191, name: "Scrambled!", points: 1, type: QuestType.MEMBERS },
  { id: 127, name: "Sea Slug", points: 1, type: QuestType.MEMBERS },
  {
    id: 2338,
    name: "Secrets of the North",
    points: 2,
    type: QuestType.MEMBERS,
  },
  { id: 128, name: "Shades of Mort'ton", points: 3, type: QuestType.MEMBERS },
  { id: 129, name: "Shadow of the Storm", points: 1, type: QuestType.MEMBERS },
  { id: 5190, name: "Shadows of Custodia", points: 2, type: QuestType.MEMBERS },
  { id: 130, name: "Sheep Herder", points: 4, type: QuestType.MEMBERS },
  { id: 133, name: "Shilo Village", points: 2, type: QuestType.MEMBERS },
  { id: 134, name: "Sins of the Father", points: 2, type: QuestType.MEMBERS },
  { id: 169, name: "Sleeping Giants", points: 1, type: QuestType.MEMBERS },
  { id: 136, name: "The Slug Menace", points: 1, type: QuestType.MEMBERS },
  { id: 137, name: "Song of the Elves", points: 4, type: QuestType.MEMBERS },
  { id: 138, name: "A Soul's Bane", points: 1, type: QuestType.MEMBERS },
  { id: 139, name: "Spirits of the Elid", points: 2, type: QuestType.MEMBERS },
  { id: 140, name: "Swan Song", points: 2, type: QuestType.MEMBERS },
  { id: 141, name: "Tai Bwo Wannai Trio", points: 2, type: QuestType.MEMBERS },
  { id: 142, name: "A Tail of Two Cats", points: 2, type: QuestType.MEMBERS },
  {
    id: 143,
    name: "Tale of the Righteous",
    points: 1,
    type: QuestType.MEMBERS,
  },
  { id: 144, name: "A Taste of Hope", points: 1, type: QuestType.MEMBERS },
  { id: 145, name: "Tears of Guthix", points: 1, type: QuestType.MEMBERS },
  { id: 146, name: "Temple of Ikov", points: 1, type: QuestType.MEMBERS },
  { id: 167, name: "Temple of the Eye", points: 1, type: QuestType.MEMBERS },
  {
    id: 147,
    name: "Throne of Miscellania",
    points: 1,
    type: QuestType.MEMBERS,
  },
  { id: 148, name: "The Tourist Trap", points: 2, type: QuestType.MEMBERS },
  { id: 149, name: "Tower of Life", points: 2, type: QuestType.MEMBERS },
  { id: 150, name: "Tree Gnome Village", points: 2, type: QuestType.MEMBERS },
  { id: 151, name: "Tribal Totem", points: 1, type: QuestType.MEMBERS },
  { id: 152, name: "Troll Romance", points: 2, type: QuestType.MEMBERS },
  { id: 153, name: "Troll Stronghold", points: 1, type: QuestType.MEMBERS },
  { id: 3512, name: "Twilight's Promise", points: 1, type: QuestType.MEMBERS },
  { id: 154, name: "Underground Pass", points: 5, type: QuestType.MEMBERS },
  { id: 156, name: "Wanted!", points: 1, type: QuestType.MEMBERS },
  { id: 157, name: "Watchtower", points: 4, type: QuestType.MEMBERS },
  { id: 158, name: "Waterfall Quest", points: 1, type: QuestType.MEMBERS },
  { id: 159, name: "What Lies Below", points: 1, type: QuestType.MEMBERS },
  { id: 3467, name: "While Guthix Sleeps", points: 5, type: QuestType.MEMBERS },
  { id: 160, name: "Witch's House", points: 4, type: QuestType.MEMBERS },
  { id: 163, name: "Zogre Flesh Eaters", points: 1, type: QuestType.MEMBERS },

  // MINI quests
  {
    id: 4,
    name: "Alfred Grimhand's Barcrawl",
    points: 0,
    type: QuestType.MINI,
  },
  { id: 3451, name: "Barbarian Training", points: 0, type: QuestType.MINI },
  { id: 5, name: "Bear Your Soul", points: 0, type: QuestType.MINI },
  { id: 20, name: "Curse of the Empty Lord", points: 0, type: QuestType.MINI },
  { id: 21, name: "Daddy's Home", points: 0, type: QuestType.MINI },
  { id: 41, name: "The Enchanted Key", points: 0, type: QuestType.MINI },
  { id: 43, name: "Enter the Abyss", points: 0, type: QuestType.MINI },
  { id: 49, name: "Family Pest", points: 0, type: QuestType.MINI },
  { id: 164, name: "The Frozen Door", points: 0, type: QuestType.MINI },
  { id: 59, name: "The General's Shadow", points: 0, type: QuestType.MINI },
  { id: 3250, name: "His Faithful Servants", points: 0, type: QuestType.MINI },
  { id: 166, name: "Hopespear's Will", points: 0, type: QuestType.MINI },
  { id: 78, name: "In Search of Knowledge", points: 0, type: QuestType.MINI },
  { id: 2306, name: "Into the Tombs", points: 0, type: QuestType.MINI },
  { id: 84, name: "Lair of Tarn Razorlor", points: 0, type: QuestType.MINI },
  { id: 89, name: "Mage Arena I", points: 0, type: QuestType.MINI },
  { id: 90, name: "Mage Arena II", points: 0, type: QuestType.MINI },
  { id: 135, name: "Skippy and the Mogres", points: 0, type: QuestType.MINI },
  { id: 5194, name: "Vale Totems", points: 0, type: QuestType.MINI },
] as const satisfies Quest[];
