import { queryOptions, useQuery } from "@tanstack/react-query";
import { useState } from "react";

import QuestionMarkImage from "~/core/assets/misc/question-mark.png";
import { cn, itemIconUrl } from "~/shared/utils";

// All collection log item icons composed into one sprite sheet, so clog
// grids render atomically with a single image request instead of one
// request per item. Generated by scripts/ts-scripts/sync-item-icons.ts;
// the manifest sits at a stable URL with a short TTL and points at a
// content-hashed, immutably-cached atlas image.
type ClogAtlasManifest = {
  atlas: string;
  width: number;
  height: number;
  cellWidth: number;
  cellHeight: number;
  icons: Record<string, [number, number]>;
};

export const clogAtlasQueryOptions = queryOptions({
  queryKey: ["clog-atlas"],
  queryFn: async (): Promise<ClogAtlasManifest> => {
    const response = await fetch("https://cdn.runeprofile.com/clog-atlas.json");
    if (!response.ok) {
      throw new Error(
        `Failed to load clog atlas manifest (${response.status})`,
      );
    }
    return response.json();
  },
  staleTime: Infinity,
  retry: 1,
});

/**
 * Item icon from the RuneProfile CDN - the one component for rendering any
 * item, collection log or not.
 *
 * Collection log items come from the sprite-sheet atlas; anything else
 * (or anything the manifest doesn't cover) falls back to the per-item
 * icon URL with a question mark for missing icons. While the manifest is
 * loading this renders an empty placeholder rather than per-item icons -
 * kicking off individual requests just to swap them out moments later is
 * the popcorn effect the atlas exists to prevent.
 */
export function ItemIcon({
  id,
  alt,
  size = 24,
  className,
}: {
  id: number;
  alt: string;
  size?: number;
  className?: string;
}) {
  const atlasQuery = useQuery(clogAtlasQueryOptions);

  const manifest = atlasQuery.data;
  const coords = manifest?.icons[id];

  if (!manifest || !coords) {
    if (atlasQuery.isPending) {
      return (
        <div className={className} style={{ width: size, height: size }} />
      );
    }
    return (
      <ItemIconImage id={id} alt={alt} size={size} className={className} />
    );
  }

  // The cell is rendered at its native size with integer background
  // offsets and scaled with a transform - scaling the background image
  // instead would put cell boundaries on fractional pixels and bleed in
  // neighboring icons.
  return (
    <div
      role="img"
      aria-label={alt}
      className={cn("flex items-center justify-center", className)}
      style={{ width: size, height: size }}
    >
      <div
        style={{
          width: manifest.cellWidth,
          height: manifest.cellHeight,
          flexShrink: 0,
          backgroundImage: `url(${manifest.atlas})`,
          backgroundPosition: `${-coords[0]}px ${-coords[1]}px`,
          imageRendering: "pixelated",
          transform: `scale(${size / manifest.cellWidth})`,
        }}
      />
    </div>
  );
}

/**
 * Single item icon fetched from the CDN by item id, with a question mark
 * fallback for icons missing from the bucket.
 */
function ItemIconImage({
  id,
  alt,
  size = 24,
  className,
}: {
  id: number;
  alt: string;
  size?: number;
  className?: string;
}) {
  const [failedId, setFailedId] = useState<number | null>(null);

  return (
    <img
      src={failedId === id ? QuestionMarkImage : itemIconUrl(id)}
      alt={alt}
      onError={() => setFailedId(id)}
      className={cn("object-contain", className)}
      style={{
        width: `${size}px`,
        height: `${size}px`,
        imageRendering: "pixelated",
      }}
    />
  );
}
